#!/home/ctf-machine/PycharmProjects/transport-starter-code-main/.venv/bin/python3
import argparse, socket, time, json, select, struct, sys, math

DATA_SIZE = 1375


class Sender:
    def __init__(self, host, port):
        self.host = host
        self.port = int(port)
        self.log("Sender starting up using port %s" % self.port)
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))
        self.waiting = False
        self.window_size = 2
        self.acknowledged_packet = set()
        self.sent_out_packets = set()
        self.change_window_counter = 0
        self.packets_sent_so_far = {}

        self.received_ack_of_current_window = set()
        self.stop_what_ack_we_want_at_this_number = -1
        self.what_we_want = set()
        self.where_are_we = 0
        self.socket.settimeout(2.0)


        self.remote_host = None
        self.remote_port = None

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def send(self, message):
        self.log("Sending message '%s'" % json.dumps(message))
        self.socket.sendto(json.dumps(message).encode("utf-8"), (self.host, self.port))

    def recv(self, socket):
        data, addr = socket.recvfrom(65535)

        # Grab the remote host/port if we don't already have it
        if self.remote_host is None:
            self.remote_host = addr[0]
            self.remote_port = addr[1]

        # Make sure we're talking to the same remote host
        if addr != (self.remote_host, self.remote_port):
            self.log("Error:  Received response from unexpected remote; ignoring")
            return None
        else:
            self.log("Received message %s" % data)
            return json.loads(data.decode("utf-8"))

    def handle_socket_input(self, conn):
        """
        Processes incoming packets on the UDP socket.
        Tracks acknowledgments and adjusts the window size.
        """
        i = 0
        size = self.window_size
        while i < size:
            try:

                if len(self.sent_out_packets) == 0:
                    self.log("All done!")
                    sys.exit(0)

                data = self.recv(conn)
                # Check if we have a new acknowledgment
                if data["type"] == "ack" or data["type"] == "fin":
                    if data['seq'] not in self.acknowledged_packet:
                        self.acknowledged_packet.add(data['seq'])
                        self.sent_out_packets -= self.acknowledged_packet

                        self.waiting = False
                        # Increase window if needed
                        if self.change_window_counter == self.window_size - 1:
                            self.window_size += 1
                            self.change_window_counter = 0
                        else:
                            self.change_window_counter += 1
                    else:
                        # Duplicate ack, temporarily expand window size
                        size += 1
            except socket.timeout:
                self.log("Timeout occurred, sending send back data")
                # print(f"debug: waw={self.where_are_we}, waw+win_size={self.where_are_we + self.window_size}", file=sys.stderr)
                self.missing_ack()

                break

            i += 1



    def handle_stdin_input(self, seq):
        """
        Reads chunks of data from standard input
        and sends them as packets.
        """
        for _ in range(self.window_size):
            data = sys.stdin.read(DATA_SIZE)
            if len(data) != 0:
                msg = {"type": "msg", "data": data, "seq": seq}
                self.sent_out_packets.add(seq)
                self.packets_sent_so_far[seq] = msg

                self.send(msg)
            else:
                msg = {"type": "fin", "data": data, "seq": seq}

                self.send(msg)
                break

            # print(f"DEBUG: sent_out_packets = {self.sent_out_packets}", file=sys.stderr)
            # if len(self.sent_out_packets) == 0:
            #     self.log("All done!")
            #     sys.exit(0)
            self.waiting = True
            seq += 1
        return seq

    def missing_ack(self):

        if self.stop_what_ack_we_want_at_this_number == -1:
            for i in range(self.where_are_we, self.where_are_we + self.window_size):
                self.what_we_want.add(i)
        else:
            for i in range(self.where_are_we, self.stop_what_ack_we_want_at_this_number):
                self.what_we_want.add(i)

        if self.what_we_want != self.received_ack_of_current_window:
            print(f"DEBUG this is the received ack of: {self.received_ack_of_current_window} and the what we want: {self.what_we_want}", file=sys.stderr)
            print(f"DEBUG this is where we are {self.where_are_we} and our window size is {self.window_size}", file=sys.stderr)
            missing_ack = self.what_we_want - self.received_ack_of_current_window
            for ack in missing_ack:
                msg = {"type": "msg", "data": self.packets_sent_so_far[ack]['data'], "seq": ack}
                self.send(msg)
        else:
            self.window_size += 1



    def handle_received_window(self):
        self.what_we_want.clear()
        self.received_ack_of_current_window.clear()

    def advance_window(self):

        self.where_are_we += self.window_size - 1
        print(f"where we are: {self.where_are_we}", file=sys.stderr)



    def run(self):
        """
        Main loop that merges socket input and standard input
        according to the window settings and waiting state.
        """
        seq = 0
        while True:
            # If not waiting, listen on both socket and STDIN
            sockets = [self.socket, sys.stdin] if not self.waiting else [self.socket]
            ready_socks = select.select(sockets, [], [], 0.1)[0]

            for conn in ready_socks:
                if conn == self.socket:
                    self.handle_socket_input(conn)
                elif conn == sys.stdin:
                    seq = self.handle_stdin_input(seq)

            self.handle_received_window()
            self.advance_window()



if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data')
    parser.add_argument('host', type=str, help="Remote host to connect to")
    parser.add_argument('port', type=int, help="UDP port number to connect to")
    args = parser.parse_args()
    sender = Sender(args.host, args.port)
    sender.run()
